[versions]
agp = "8.11.2"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.11.0"
composeBom = "2024.09.00"
navigationComposeVersion = "2.9.6"
serialization = "1.8.0"
hiltNavigationCompose = "1.2.0"
retrofitVersion = "3.0.0"
loggingInterceptorVersion = "5.0.0"
composeTest = "1.10.0"
coilVersion = "3.0.4"
hiltVersion = "2.57.1"
mockitoCoreVersion = "5.10.0"
roomVersion = "2.8.4"
mockitoKotlinKotlinVersion ="6.1.0"
androidxCoreTestingVersion ="2.2.0"
appcompat = "1.7.1"
material = "1.13.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationComposeVersion" }
kotlinx-serialization-json = {group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization"}
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
# Retrofit
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofitVersion" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofitVersion" }
# Logging Interceptor
httpLoggingInterceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "loggingInterceptorVersion" }
androidx-compose-ui-test-junit = {group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "composeTest"}
androidx-compose-ui-test-manifest = {group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "composeTest"}
# Coil
coil-compose = {group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coilVersion"}
coil-network = {group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coilVersion"}
# Hilt
dagger-hilt-android = {group = "com.google.dagger", name = "hilt-android", version.ref = "hiltVersion"}
dagger-hilt-android-compiler = {group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hiltVersion"}
# Mockito
mockito-core = {group = "org.mockito", name = "mockito-core", version.ref = "mockitoCoreVersion"}
mockito-android = {group = "org.mockito", name = "mockito-android", version.ref = "mockitoCoreVersion"}
#Mockito Kotlin
mockito-kotlin = {group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockitoKotlinKotlinVersion"}
# Room
room-runtime = {group = "androidx.room", name = "room-runtime", version.ref = "roomVersion"}
room-compiler= {group = "androidx.room", name = "room-compiler", version.ref = "roomVersion"}
room-testing = {group = "androidx.room", name = "room-testing", version.ref = "roomVersion"}
# Arch components core testing
androidx-core-testing = {group = "androidx.arch.core", name = "core-testing", version.ref = "androidxCoreTestingVersion"}
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = {id = "org.jetbrains.kotlin.plugin.serialization" , version.ref = "kotlin"}
android-library = { id = "com.android.library", version.ref = "agp" }